name: Build
on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: build-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'

      - name: Build Plugin
        run: ./gradlew verifyPluginProjectConfiguration verifyPluginStructure buildPlugin -PuseLocalIde=false
